import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getLogtoContext, signIn, signOut } from "@logto/next/server-actions";
import "./globals.css";
import { logtoConfig } from "./logto";
import SignIn from "./components/SignIn";
import SignOut from "./components/SignOut";
import AppShell from "./components/AppShell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const { isAuthenticated, claims } = await getLogtoContext(logtoConfig);

  const accountAction = isAuthenticated ? (
    <SignOut
      onSignOut={async () => {
        "use server";
        await signOut(logtoConfig);
      }}
    />
  ) : (
    <SignIn
      onSignIn={async () => {
        "use server";
        await signIn(logtoConfig);
      }}
    />
  );

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-[#0E2A23] text-[#F2EBDD]">
        <AppShell
          isAuthenticated={isAuthenticated}
          displayName={claims?.sub}
          accountAction={accountAction}
        >
          {children}
        </AppShell>
      </body>
    </html>
  );
}
